[osx] re-enable notarization entitlements
amirrajan/rubymotion-templates pull request #25
Opened 2019-08-30 21:04 UTC by digitalmoksha

I was running into two issues during `rake notarize`:

1. Re-signing the app bundle without using an entitlements file strips any existing entitlements.  So the final file was successfully notarized, but there were not entitlements.

1. After re-enabling the entitlement file creation (which creates it based on the entitlements in the existing app), the additional `App.build('MacOSX')` step in the `rake notarize` task would re-create an unsigned app bundle, which of course doesn't have the entitlements.

   Instead, we now assume that a successful `rake build:release` has been done, the notarize step takes that app and notarizes it.

2019-08-30 21:07 UTC, digitalmoksha commented
@ediathome could you take a look at the changes I'm proposing, and make sure they work for you as well?

After digging into some weird app behavior, I realized my notarized app did have any entitlements!  😈

2019-09-02 08:21 UTC, ediathome commented
> I was running into two issues during `rake notarize`:
> 
> 1. Re-signing the app bundle without using an entitlements file strips any existing entitlements.  So the final file was successfully notarized, but there were not entitlements.
> 2. After re-enabling the entitlement file creation (which creates it based on the entitlements in the existing app), the additional `App.build('MacOSX')` step in the `rake notarize` task would re-create an unsigned app bundle, which of course doesn't have the entitlements.

Makes sense - just tested it and it works

>    Instead, we now assume that a successful `rake build:release` has been done, the notarize step takes that app and notarizes it.

Maybe we can add a check that the build file exists and if it doesn't print a reminder to run `rake build:release` before notarization.

> 
> I also added a couple validations of the resulting `codesign` calls. Additional checks can be added as needed.

Very cool! This is much better as you can now see immediately where problems lie.

2019-09-02 08:29 UTC, ediathome requested changes
Here is a suggestion for checking for app_bundle. We should call this in the notarize method before all other steps...

```
      # Check if the app bundle file exists, otherwise remind the 
      # user to run rake build:release
      def check_app_bundle_exist
        return true if File.exist?(app_bundle)
        show_as_failed("No app bundle found at '#{app_bundle}'! ")
        raise "Please run \n\n\trake build:release \n\nbefore notarizing!"
      end
```

2019-09-03 00:25 UTC, digitalmoksha commented
Great idea @ediathome!  I've pushed the changes for it.  Take a look when you get a chance.

@amirrajan if @ediathome is fine with the changes, can you review and merge if it's ok?

2019-09-06 20:37 UTC, merged